/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomIdRouteImport } from './routes/room/$id'
import { Route as RoomIdXAdminKeyRouteImport } from './routes/room/$id.x.$adminKey'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomIdRoute = RoomIdRouteImport.update({
  id: '/room/$id',
  path: '/room/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomIdXAdminKeyRoute = RoomIdXAdminKeyRouteImport.update({
  id: '/x/$adminKey',
  path: '/x/$adminKey',
  getParentRoute: () => RoomIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/room/$id': typeof RoomIdRouteWithChildren
  '/room/$id/x/$adminKey': typeof RoomIdXAdminKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/room/$id': typeof RoomIdRouteWithChildren
  '/room/$id/x/$adminKey': typeof RoomIdXAdminKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/room/$id': typeof RoomIdRouteWithChildren
  '/room/$id/x/$adminKey': typeof RoomIdXAdminKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/room/$id' | '/room/$id/x/$adminKey'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/room/$id' | '/room/$id/x/$adminKey'
  id: '__root__' | '/' | '/room/$id' | '/room/$id/x/$adminKey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RoomIdRoute: typeof RoomIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$id': {
      id: '/room/$id'
      path: '/room/$id'
      fullPath: '/room/$id'
      preLoaderRoute: typeof RoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$id/x/$adminKey': {
      id: '/room/$id/x/$adminKey'
      path: '/x/$adminKey'
      fullPath: '/room/$id/x/$adminKey'
      preLoaderRoute: typeof RoomIdXAdminKeyRouteImport
      parentRoute: typeof RoomIdRoute
    }
  }
}

interface RoomIdRouteChildren {
  RoomIdXAdminKeyRoute: typeof RoomIdXAdminKeyRoute
}

const RoomIdRouteChildren: RoomIdRouteChildren = {
  RoomIdXAdminKeyRoute: RoomIdXAdminKeyRoute,
}

const RoomIdRouteWithChildren =
  RoomIdRoute._addFileChildren(RoomIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RoomIdRoute: RoomIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
